global:
  resolve_timeout: 5m

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts'
        send_resolved: true

route:
  group_by: ['slack']
  receiver: 'slack-notifications'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
