apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-cm
    app.kubernetes.io/part-of: argocd
data:
  service.slack: |
    token: <https://hooks.slack.com/services/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>

  trigger.sync-failed: |
    - when: app.status.sync.status == 'OutOfSync' && app.status.operationState.phase in ['Error', 'Failed']
      send: [slack]
      oncePer: app.metadata.name

  template.slack: |
    slack:
      message: |
        *ArgoCD Sync Failure* 🚨
        App: *{{.app.metadata.name}}*
        Status: *{{.app.status.sync.status}}*
        Health: *{{.app.status.health.status}}*
        URL: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
