apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alerts
  namespace: monitoring-dev
  labels:
    release: prom
    role: alert-rules
spec:
  groups:
    - name: pod-alerts
      rules:
        - alert: HighPodRestart
          expr: increase(kube_pod_container_status_restarts_total[10m]) > 3
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High pod restart count"
            description: "Pod has restarted more than 3 times in 10 minutes."

        - alert: HighAppLatency
          expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High application latency"
            description: "95th percentile latency is above 1s in the last 5 minutes."

        - alert: HighHttp5xxErrorRate
          expr: rate(http_requests_total{status=~"5.."}[5m]) > 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "High HTTP 5xx error rate"
            description: "More than 1 HTTP 5xx error per second in the last 5 minutes."
