apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","metadata":{"annotations":{"meta.helm.sh/release-name":"prom","meta.helm.sh/release-namespace":"monitoring-dev"},"creationTimestamp":"2025-05-17T05:30:12Z","generation":1,"labels":{"app":"kube-prometheus-stack-prometheus","app.kubernetes.io/instance":"prom","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/part-of":"kube-prometheus-stack","app.kubernetes.io/version":"72.4.0","chart":"kube-prometheus-stack-72.4.0","heritage":"Helm","release":"prom"},"name":"prom-kube-prometheus-stack-prometheus","namespace":"monitoring-dev","resourceVersion":"1283614","uid":"25d60a55-8a8a-427a-beac-499bba8cff3d"},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["prometheus"]},{"key":"prometheus","operator":"In","values":["prom-kube-prometheus-stack-prometheus"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"alerting":{"alertmanagers":[{"apiVersion":"v2","name":"prom-kube-prometheus-stack-alertmanager","namespace":"monitoring-dev","pathPrefix":"/","port":"http-web"}]},"automountServiceAccountToken":true,"enableAdminAPI":false,"evaluationInterval":"30s","externalUrl":"http://prom-kube-prometheus-stack-prometheus.monitoring-dev:9090","hostNetwork":false,"image":"quay.io/prometheus/prometheus:v3.3.1","listenLocal":false,"logFormat":"logfmt","logLevel":"info","paused":false,"podMonitorNamespaceSelector":{},"podMonitorSelector":{"matchLabels":{"release":"prom"}},"portName":"http-web","probeNamespaceSelector":{},"probeSelector":{"matchLabels":{"release":"prom"}},"replicas":1,"retention":"10d","routePrefix":"/","ruleNamespaceSelector":{},"ruleSelector":{"matchLabels":{"release":"prom"}},"scrapeConfigNamespaceSelector":{},"scrapeConfigSelector":{"matchLabels":{"release":"prom"}},"scrapeInterval":"30s","securityContext":{"fsGroup":2000,"runAsGroup":2000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"prom-kube-prometheus-stack-prometheus","serviceMonitorNamespaceSelector":{},"serviceMonitorSelector":{"matchLabels":{"release":"prom"}},"shards":1,"tsdb":{"outOfOrderTimeWindow":"0s"},"version":"v3.3.1","walCompression":true},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-05-17T05:38:25Z","message":"","observedGeneration":1,"reason":"","status":"True","type":"Available"},{"lastTransitionTime":"2025-05-17T05:38:25Z","message":"","observedGeneration":1,"reason":"","status":"True","type":"Reconciled"}],"paused":false,"replicas":1,"selector":"app.kubernetes.io/instance=prom-kube-prometheus-stack-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=prom-kube-prometheus-stack-prometheus,prometheus=prom-kube-prometheus-stack-prometheus","shardStatuses":[{"availableReplicas":1,"replicas":1,"shardID":"0","unavailableReplicas":0,"updatedReplicas":1}],"shards":1,"unavailableReplicas":0,"updatedReplicas":1}}
    meta.helm.sh/release-name: prom
    meta.helm.sh/release-namespace: monitoring-dev
  creationTimestamp: "2025-05-17T05:30:12Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prom
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 72.4.0
    chart: kube-prometheus-stack-72.4.0
    heritage: Helm
    release: prom
  name: prom-kube-prometheus-stack-prometheus
  namespace: monitoring-dev
  resourceVersion: "1283809"
  uid: 25d60a55-8a8a-427a-beac-499bba8cff3d
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - prometheus
            - key: prometheus
              operator: In
              values:
              - prom-kube-prometheus-stack-prometheus
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: prom-kube-prometheus-stack-alertmanager
      namespace: monitoring-dev
      pathPrefix: /
      port: http-web
  automountServiceAccountToken: true
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: http://prom-kube-prometheus-stack-prometheus.monitoring-dev:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v3.3.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: prom
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: prom
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      role: alert-rules
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: prom
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: prom-kube-prometheus-stack-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: prom
  shards: 1
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v3.3.1
  walCompression: true
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-17T05:41:49Z"
    message: ""
    observedGeneration: 1
    reason: ""
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-17T05:41:49Z"
    message: ""
    observedGeneration: 1
    reason: ""
    status: "True"
    type: Reconciled
  paused: false
  replicas: 1
  selector: app.kubernetes.io/instance=prom-kube-prometheus-stack-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=prom-kube-prometheus-stack-prometheus,prometheus=prom-kube-prometheus-stack-prometheus
  shardStatuses:
  - availableReplicas: 1
    replicas: 1
    shardID: "0"
    unavailableReplicas: 0
    updatedReplicas: 1
  shards: 1
  unavailableReplicas: 0
  updatedReplicas: 1
