prometheus:
  enabled: true
  prometheusSpec:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1
    ruleSelector:
      matchLabels:
        release: prom
        role: alert-rules

prometheusOperator:
  enabled: true
  resources:
    requests:
      memory: 500Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m
  admissionWebhooks:
    enabled: false  # Disable to speed up install

grafana:
  enabled: true
  resources:
    requests:
      memory: 500Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m

prometheus-node-exporter:
  enabled: false  # Disabled for Minikube

kube-state-metrics:
  enabled: true
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m

alertmanager:
  enabled: false  # Disable to save resources
